### ISSUE TITLE
Problem ocurred when i try the installation

### ISSUE THREAD

**Issue by paulolimac** [Borisvl/Pdf4Eclipse#24]
Hello everybody!

Im having a message exception when i try to install the Pdf4Eclipse.

The message is:

> **problem ocurred**:  'installing Software' has encountered a problem. An error ocurred while installing the items.
> 
> **Details**: An error occurred while installing the items
> - session context was:(profile=epp.package.jee, phase=org.eclipse.equinox.internal.p2.engine.phases.Install, operand=null --> [R]de.vonloesch.pdf4Eclipse 1.1.0.201204091136, action=).
> - Failed to prepare partial IU: [R]de.vonloesch.pdf4Eclipse 1.1.0.201204091136.

Im using:
- Eclipse EE Juno  (Build id: 20120614-1722)
- Openjdk 7
- Ubuntu 12.04

**Some advice?**

**Comment by paulolimac** [comment]
### More informations:

Making some more attempts, I don't haved success.

The details, below:

#### Attempt 1:
- Action: Download the Eclipse in _tar.gz_ and installing the Pdf4Eclipse by the _Eclipse Market_
- Result: fail
- Resources:
  - EclipseEE Juno IDE Java x64 tar.gz
  - Openjdk-7-jdk, open-7-jre
  - Pdf4Eclipse (by the Eclipse Market)
  - Ubuntu Precise 12.04 - x64
- Process:
  1. I went to the Eclipse site and downloaded the _EclipseEE Juno_ in tar.gz format (not the _Eclipse Classic_).
  2. Unziped the EclipseEE.tar.gz in my _home folder_
  3. Installed the java: 'sudo apt-get install openjdk-7-jdk openjdk-7-jre'
  4. Running the _EclipseEE IDE_, I'm clicked on the menu 'Help -> Eclipse Market...'
  5. In the _Eclipse Market_, checked the Pdf4Eclipse plugin
  6. In my observation, the plugin was downloaded (some folders with the plugin's name are included in the Eclipse-plugin folder)
  7. The Eclipse asked by the installation, and that is confirmed
  8. A pop-up is showed, with the error message:

> **problem ocurred**:  'installing Software' has encountered a problem. An error ocurred while installing the items.
> 
> **Details**: An error occurred while installing the items
> - session context was:(profile=epp.package.jee, phase=org.eclipse.equinox.internal.p2.engine.phases.Install, operand=null --> [R]de.vonloesch.pdf4Eclipse 1.1.0.201204091136, action=).
> - Failed to prepare partial IU: [R]de.vonloesch.pdf4Eclipse 1.1.0.201204091136.

#### Attempt 2:
- Action: Download the Eclipse in _tar.gz_ and installing the Pdf4Eclipse by the _Install New Software_
- Result: fail
- Resources:
  - EclipseEE Juno IDE Java x64 tar.gz
  - Openjdk-7-jdk, open-7-jre
  - Pdf4Eclipse (by the Install New Software)
  - Ubuntu Precise 12.04 - x64
- Process:
  1. Equals with the previous _Attempt_: steps 1 to 3
  2. Running the _EclipseEE IDE_, I'm clicked on the menu 'Help -> Install new software...'
  3. In the _Install new software_, configured the Pdf4Eclipse repository.
  4. In my observation, the plugin was downloaded (some folders with the plugin's name are included in the Eclipse-plugin folder)
  5. The Eclipse asked by the installation, and that is confirmed
  6. A pop-up is showed, with the same error message of the _Attempt 1_

#### Attempt 3 (and Attempt 4):
- Action: Trying different JDK's (openjdk-6 and oraclejdk-7)
- Result: fail
- Resources:
  - EclipseEE Juno IDE Java x64 tar.gz
  - Openjdk-6-jdk, openjdk-6-jre, oracle-7-jdk
  - Pdf4Eclipse (by the Install New Software)
  - Ubuntu Precise 12.04 - x64
- Process:
  1. Installed the openjdk-6 and oracle-7-jdk (and others packages to support them)
  2. Changed the active JDK in the Ubuntu 12.04 - x64
  3. Executed the steps to install the plugin, similar with the previous attempts
  4. Resulted the same pop-up was showed, with the same error message

#### Attempt 5:
- Action: Tried to Install by the Texlipse repository
- Result: fail
- Resources:
  - EclipseEE Juno IDE Java x64 tar.gz
  - Openjdk-7-jdk
  - Texlipse (by the Install New Software)
  - Ubuntu Precise 12.04 - x64
- Process:
  1. Similar to the Attempt 2, but using the Texlipse repository URL
  2. Executed the steps to install the plugin, similar with the previous attempts...
  3. ...and the same pop-up was showed, with the same error message

Well, is that all ☹

---

But, thanks to the plugin developer(s). I used it a few months ago, in the Eclipse 3.x. And it works like a charm with the Texlipse  ☻

**Comment by paulolimac** [comment]
Another informations to support that issue: the Error Log produced by _Eclipse Error Log_

Below, the **Error Log**:

---

```

!SESSION 2012-08-04 07:26:38.100 -----------------------------------------------
eclipse.buildId=I20120608-1400
java.version=1.7.0_03
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.jee.product

---

!ENTRY org.eclipse.equinox.p2.publisher.eclipse 2 0 2012-08-05 19:25:55.711
!MESSAGE An error occurred while loading the manifest /home/paulo/Documents/Development/eclipse/plugins/de.vonloesch.pdf4Eclipse_1.1.0.201204091136.jar.
!STACK 0
java.util.zip.ZipException: error in opening zip file
    at java.util.zip.ZipFile.open(Native Method)
    at java.util.zip.ZipFile.<init>(ZipFile.java:131)
    at org.eclipse.equinox.p2.publisher.eclipse.BundlesAction.basicLoadManifest(BundlesAction.java:576)
    at org.eclipse.equinox.p2.publisher.eclipse.BundlesAction.loadManifest(BundlesAction.java:562)
    at org.eclipse.equinox.p2.publisher.eclipse.BundlesAction.createBundleDescription(BundlesAction.java:555)
    at org.eclipse.equinox.internal.p2.touchpoint.eclipse.PublisherUtil.createBundleIU(PublisherUtil.java:29)
    at org.eclipse.equinox.internal.p2.touchpoint.eclipse.EclipseTouchpoint.prepareIU(EclipseTouchpoint.java:224)
    at org.eclipse.equinox.internal.p2.touchpoint.eclipse.EclipseTouchpoint.initializeOperand(EclipseTouchpoint.java:185)
    at org.eclipse.equinox.internal.p2.engine.Phase.initializeTouchpointParameters(Phase.java:223)
    at org.eclipse.equinox.internal.p2.engine.Phase.mainPerform(Phase.java:151)
    at org.eclipse.equinox.internal.p2.engine.Phase.perform(Phase.java:92)
    at org.eclipse.equinox.internal.p2.engine.PhaseSet.perform(PhaseSet.java:47)
    at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:75)
    at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:44)
    at org.eclipse.equinox.p2.operations.ProvisioningSession.performProvisioningPlan(ProvisioningSession.java:174)
    at org.eclipse.equinox.p2.operations.ProfileModificationJob.runModal(ProfileModificationJob.java:79)
    at org.eclipse.equinox.p2.operations.ProvisioningJob.run(ProvisioningJob.java:177)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY org.eclipse.equinox.p2.touchpoint.eclipse 4 0 2012-08-05 19:25:55.768
!MESSAGE The bundle manifest could not be read: /home/paulo/Documents/Development/eclipse/plugins/de.vonloesch.pdf4Eclipse_1.1.0.201204091136.jar

!ENTRY org.eclipse.equinox.p2.engine 4 4 2012-08-05 19:25:55.771
!MESSAGE An error occurred while installing the items
!SUBENTRY 1 org.eclipse.equinox.p2.engine 4 0 2012-08-05 19:25:55.771
!MESSAGE session context was:(profile=epp.package.jee, phase=org.eclipse.equinox.internal.p2.engine.phases.Install, operand=null --> [R]de.vonloesch.pdf4Eclipse 1.1.0.201204091136, action=).
!SUBENTRY 1 org.eclipse.equinox.p2.touchpoint.eclipse 4 0 2012-08-05 19:25:55.771
!MESSAGE Failed to prepare partial IU: [R]de.vonloesch.pdf4Eclipse 1.1.0.201204091136.

```

**Comment by paulolimac** [comment]
## Success!!!

...partially, but pdf4Eclipse is running!

### In my Attempt 6:

I installed a older version of the PDF4Eclipse.

Going to the menu `Window -> Install new Software...` I marked in PDF4Eclipse the **installation of version 1.0.0 and that resulted in good news**.

Trying the **installation of version 1.0.1 I had success** too.

But i had failure to try the _installation of the versions 1.0.2 and the newer 1.1.0_.

Well, if someone have the same problem, maybe this install setup can solve the problem :)
